version: '3.1'
services:

  # first
  zoo1:
    image: zookeeper:3.6
    hostname: zoo1
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
    volumes:
      - ./conf/zoo.cfg.1:/conf/zoo.cfg
  exp1:
    image: dabealu/zookeeper-exporter
    ports:
      - 9141:9141
    command: --zk-hosts="zoo1:2181"

  # second
  zoo2:
    image: zookeeper:3.6
    hostname: zoo2
    ports:
      - 2182:2181
    environment:
      ZOO_MY_ID: 2
    volumes:
      - ./conf/zoo.cfg.2:/conf/zoo.cfg
  exp2:
    image: dabealu/zookeeper-exporter
    ports:
      - 9142:9141
    command: --zk-hosts="zoo2:2181"

  # third
  zoo3:
    ##### Uncomment block below and comment 'image' parameter in order to test timeout
    # build:
    #   context: zoo-timeout
    # privileged: true  # Needed for iptables drop rule to work in custom entrypoint script
    ##### End
    image: zookeeper:3.6
    hostname: zoo3
    ports:
      - 2183:2181
    environment:
      ZOO_MY_ID: 3
    volumes:
      - ./conf/zoo.cfg.3:/conf/zoo.cfg
  exp3:
    image: dabealu/zookeeper-exporter
    ports:
      - 9143:9141
    command: --zk-hosts="zoo3:2181" --timeout=5

  # multitarget
  exp123:
    image: dabealu/zookeeper-exporter
    # build:
    #   context: .
    ports:
      - 9144:9141
    command: --zk-hosts="zoo1:2181,zoo2:2181,zoo3:2181" --timeout=5

  # prometheus server
  prometheus:
    image: prom/prometheus:latest
    ports: 
      - 9090:9090
    entrypoint: >
      prometheus
        --config.file='/etc/prometheus/prometheus.yml'
        --storage.tsdb.path='data'
        --web.listen-address='0.0.0.0:9090'
    volumes:
      - ./conf/prometheus.yml:/etc/prometheus/prometheus.yml
