service_list: []
dependencies: ~
start_dependencies: []
proc_list:
    - proc_name: zookeeper_exporter
      proc_num_min: ~
      proc_num_max: ~
      pid_file: ~
port_list: []
start_script: ""
stop_script: ""
restart_script: ""
install_prescript: ""
install_postscript: ""
update_prescript: ""
update_postscript: ""
rollback_prescript: ""
rollback_postscript: ""
proc_guard: stopStart
port_guard: stopStart
user: easyops:easyops
